name: OWASP ZAP Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Start Spring Boot App
        run: |
          ./gradlew bootRun &
          sleep 30  # Allow time for server to start

      - name: Set up reports directory
        run: |
          mkdir -p zap-reports
          chmod -R 777 zap-reports

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: "http://localhost:8080"
          docker_name: "zaproxy/zap-stable"
          cmd_options: "-a -r  zap-reports/zap-report.html -J zap-reports/zap-report.json -w zap-reports/zap-report.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload ZAP Reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-reports
          path: |
            zap-reports
